---
title: "Untitled"
output: html_document
date: "2023-11-16"
---


```{r}
library(dplyr)
library(readr)  # for reading CSV files
setwd("C:\\Users\\sowja\\OneDrive\\Desktop\\DSC465\\Project new")

# Read CSV files for all the years

data_2015 <- read.csv("data_2015.csv")
data_2016 <- read.csv("data_2016.csv")
data_2017 <- read.csv("data_2017.csv")
data_2018 <- read.csv("data_2018.csv")
data_2019 <- read.csv("data_2019.csv")
data_2020 <- read.csv("data_2020.csv")
data_2021 <- read.csv("data_2021.csv")
data_2022 <- read.csv("data_2022.csv")


data_2022$Happiness.score <- as.numeric(gsub(",", ".", data_2022$Happiness.score))
data_2022$Dystopia.residual <- as.numeric(gsub(",", ".", data_2022$Dystopia.residual))
data_2022$GDP <- as.numeric(gsub(",", ".", data_2022$GDP))
data_2022$Social.support <- as.numeric(gsub(",", ".", data_2022$Social.support))
data_2022$Healthy.life.expectancy <- as.numeric(gsub(",", ".", data_2022$Healthy.life.expectancy))
data_2022$Freedom.to.make.life.choices <- as.numeric(gsub(",", ".", data_2022$Freedom.to.make.life.choices))
data_2022$Generosity <- as.numeric(gsub(",", ".", data_2022$Generosity))
data_2022$Perceptions.of.corruption <- as.numeric(gsub(",", ".", data_2022$Perceptions.of.corruption))

#Adding Year column
data_2015$Year <- 2015
data_2016$Year <- 2016
data_2017$Year <- 2017
data_2018$Year <- 2018
data_2019$Year <- 2019
data_2020$Year <- 2020
data_2021$Year <- 2021
data_2022$Year <- 2022

```

```{r}
# Combine the datasets
combined_data <- bind_rows(data_2015,data_2016,data_2017,data_2018,data_2019,data_2020, data_2021, data_2022)
# Using gsub to remove asterisks from country names
combined_data$Country <- gsub("\\*", "", combined_data$Country)

# Write the combined data to a new CSV file
write.csv(combined_data, "combined_happiness_report.csv", row.names = FALSE)

head(combined_data)
```
```{r}
library(ggplot2)

# Histogram of Happiness Score
ggplot(combined_data, aes(x = Happiness.score)) +
  geom_histogram(binwidth = 0.5, fill = "blue", color = "black") +
  theme_minimal() +
  labs(title = "Distribution of Happiness Scores", x = "Happiness Score", y = "Count")
```

```{r}
# Scatter plot of GDP per Capita vs Happiness Score with separate panels for each Year and colored by Health Life Expectancy
      ggplot(combined_data, aes(x = GDP, y = Happiness.score)) +
        geom_point(alpha = 0.7) +
        facet_wrap(~ Year) +  # Creates separate panels for each year
        scale_color_gradient(low = "blue", high = "red") +  # Use a gradient color scale for Health Life Expectancy
        theme_minimal() +
        labs(title = "GDP per Capita vs Happiness Score ", 
             x = "GDP per Capita", 
             y = "Happiness Score")
```

